spring:
  datasource:
    url: jdbc:mysql://localhost:3310/guestbook?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: education
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  thymeleaf:
    cache: false
server:
  port: 8080